-- ----------------------------
-- Table structure for ETL
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."ETL" (
  "SCHEMA_PRC" VARCHAR2(100 BYTE) VISIBLE,
  "SCHEMA_STG" VARCHAR2(100 BYTE) VISIBLE,
  "TABLA" VARCHAR2(100 BYTE) VISIBLE,
  "ID_TABLE" NUMBER VISIBLE,
  "FIELD" VARCHAR2(100 BYTE) VISIBLE,
  "RULE_EQUAL" VARCHAR2(255 BYTE) VISIBLE,
  "RULE_REGEX" VARCHAR2(255 BYTE) VISIBLE,
  "RULE_FIELD" VARCHAR2(255 BYTE) VISIBLE,
  "RULE_NULL" VARCHAR2(255 BYTE) VISIBLE,
  "RULE_MAX" VARCHAR2(255 BYTE) VISIBLE,
  "RULE_MIN" VARCHAR2(255 BYTE) VISIBLE,
  "RULE_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "DEFAULT_VALUE" VARCHAR2(255 BYTE) VISIBLE,
  "REPLACE_VALUE" VARCHAR2(255 BYTE) VISIBLE,
  "RANGE_MIN" VARCHAR2(255 BYTE) VISIBLE,
  "RANGE_MAX" VARCHAR2(255 BYTE) VISIBLE,
  "RULE_MANDATORY" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;


-- ----------------------------
-- Table structure for PARAMETRICA
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."PARAMETRICA" (
  "S_STAGE" VARCHAR2(50 BYTE) VISIBLE,
  "S_PROCESSED" VARCHAR2(50 BYTE) VISIBLE,
  "S_INSIS" VARCHAR2(50 BYTE) VISIBLE,
  "T_STAGE" VARCHAR2(50 BYTE) VISIBLE,
  "T_PROCESSED" VARCHAR2(50 BYTE) VISIBLE,
  "T_INSIS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDEN" NUMBER VISIBLE,
  "PRIORIDAD" NUMBER VISIBLE,
  "PATH" VARCHAR2(100 BYTE) VISIBLE,
  "QUERY" VARCHAR2(1000 BYTE) VISIBLE,
  "PK" VARCHAR2(20 BYTE) VISIBLE,
  "HEATER" VARCHAR2(20 BYTE) VISIBLE,
  "USR_STAGE" VARCHAR2(20 BYTE) VISIBLE,
  "PWD_STAGE" VARCHAR2(50 BYTE) VISIBLE,
  "AUT_STAGE" VARCHAR2(50 BYTE) VISIBLE,
  "USR_PROCESSED" VARCHAR2(20 BYTE) VISIBLE,
  "PWD_PROCESSED" VARCHAR2(50 BYTE) VISIBLE,
  "AUT_PROCESSED" VARCHAR2(50 BYTE) VISIBLE,
  "USR_INSIS" VARCHAR2(20 BYTE) VISIBLE,
  "PWD_INSIS" VARCHAR2(50 BYTE) VISIBLE,
  "AUT_INSIS" VARCHAR2(50 BYTE) VISIBLE,
  "AUTORREFERENCIAL" NUMBER VISIBLE,
  "MIGRADA" NUMBER VISIBLE DEFAULT 1
   ,
  "BATCH_SIZE" VARCHAR2(20 BYTE) VISIBLE,
  "T_TRACE" VARCHAR2(50 BYTE) VISIBLE,
  "ESTADO" NUMBER VISIBLE,
  "QUERY_UPD" VARCHAR2(1000 BYTE) VISIBLE,
  "URL_INS" VARCHAR2(200 BYTE) VISIBLE,
  "URL_UPD" VARCHAR2(200 BYTE) VISIBLE,
  "T_REJECT" VARCHAR2(50 BYTE) VISIBLE,
  "TYPE_API" NUMBER VISIBLE,
  "TEMPLATE" VARCHAR2(100 BYTE) VISIBLE,
  "ID_TABLE" VARCHAR2(100 BYTE) VISIBLE,
  "QUERY_STG" VARCHAR2(1000 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ADDRESS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_ADDRESS_LOG" (
  "ID_VIGENTE" NUMBER(38,0) VISIBLE,
  "ID_INSIS" NUMBER(38,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" TIMESTAMP(6) VISIBLE,
  "TIMESTAMP_GET" TIMESTAMP(6) VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "NAME_JSON" VARCHAR2(50 BYTE) VISIBLE,
  "S_UPDATE" DATE VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ADDRESS_REJECT
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_ADDRESS_REJECT" (
  "ID" NUMBER(38,0) VISIBLE,
  "ERROR" VARCHAR2(100 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_AGENTS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_AGENTS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_BANKS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_BANKS_LOG" (
  "ID_VIGENTE" NUMBER(38,0) VISIBLE,
  "ID_INSIS" NUMBER(38,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" TIMESTAMP(6) VISIBLE,
  "TIMESTAMP_GET" TIMESTAMP(6) VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "NAME_JSON" VARCHAR2(50 BYTE) VISIBLE,
  "S_UPDATE" DATE VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_BANKS_REJECT
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_BANKS_REJECT" (
  "ID" NUMBER(38,0) VISIBLE,
  "ERROR" VARCHAR2(100 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_BANK_ACCOUNT_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_BANK_ACCOUNT_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CLIENTS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_CLIENTS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CLIENT_CHANGES_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_CLIENT_CHANGES_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CONTACTS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_CONTACTS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CONTACT_PERSONS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_CONTACT_PERSONS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CREDITORS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_CREDITORS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CREDIT_CARD_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_CREDIT_CARD_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_EXPERTS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_EXPERTS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_INSURERS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_INSURERS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE,
  "S_UPDATE" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_INSURERS_REJECT
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_INSURERS_REJECT" (
  "ID" NUMBER(38,0) VISIBLE,
  "ERROR" VARCHAR2(100 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_OFFICES_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_OFFICES_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_GROUPS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_PEOPLE_GROUPS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_ID_LIST_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_PEOPLE_ID_LIST_LOG" (
  "ID_VIGENTE" NUMBER(38,0) VISIBLE,
  "ID_INSIS" NUMBER(38,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" TIMESTAMP(6) VISIBLE,
  "TIMESTAMP_GET" TIMESTAMP(6) VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "NAME_JSON" VARCHAR2(50 BYTE) VISIBLE,
  "S_UPDATE" DATE VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_ID_LIST_REJECT
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_PEOPLE_ID_LIST_REJECT" (
  "ID" NUMBER(38,0) VISIBLE,
  "ERROR" VARCHAR2(100 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_PEOPLE_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" TIMESTAMP(6) VISIBLE,
  "TIMESTAMP_GET" TIMESTAMP(6) VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "NAME_JSON" VARCHAR2(50 BYTE) VISIBLE,
  "S_UPDATE" DATE VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_REJECT
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_PEOPLE_REJECT" (
  "ID" NUMBER(38,0) VISIBLE,
  "ERROR" VARCHAR2(100 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ROLE_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_ROLE_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_SALES_CHANNEL_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_SALES_CHANNEL_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_STAFF_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_STAFF_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_USER_ACCOUNTS_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."P_USER_ACCOUNTS_LOG" (
  "ID_VIGENTE" NUMBER(10,0) VISIBLE,
  "ID_INSIS" NUMBER(10,0) VISIBLE,
  "PATH_JSON" VARCHAR2(1000 BYTE) VISIBLE,
  "PATH_API" VARCHAR2(1000 BYTE) VISIBLE,
  "TIMESTAMP_POST" DATE VISIBLE,
  "TIMESTAMP_GET" DATE VISIBLE,
  "ERROR_POST" VARCHAR2(1000 BYTE) VISIBLE,
  "ERROR_GET" VARCHAR2(1000 BYTE) VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STATES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."STATES" (
  "STATE_ID" NUMBER VISIBLE,
  "STATE" VARCHAR2(20 BYTE) VISIBLE,
  "DESCRIPTION" VARCHAR2(200 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for TEMP_LOG
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_TRACE"."TEMP_LOG" (
  "ID_INSIS" NUMBER(38,0) VISIBLE,
  "NAME_JSON" VARCHAR2(50 BYTE) VISIBLE,
  "ORDER_INS" NUMBER(38,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Function structure for INS_REJECTED
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "INSIS_PEOPLE_V10_TRACE"."INS_REJECTED" AS
BEGIN
    EXECUTE IMMEDIATE
    'MERGE INTO INSIS_PEOPLE_V10_TRACE.rejected_insis t ' ||
    ' USING (SELECT ID_VIGENTE FROM '|| TABLE_LOG ||
           ' WHERE ID_INSIS IS NULL ) d on (t.ID_VIGENTE = d.ID_VIGENTE ) ' ||
   ' WHEN NOT matched THEN INSERT (ID_VIGENTE, TABLE_NAME)' ||
    'VALUES (d.ID_VIGENTE , TABLE_LOG)';
END INS_REJECTED;
/

-- ----------------------------
-- Function structure for INS_REJECTED2
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "INSIS_PEOPLE_V10_TRACE"."INS_REJECTED2" AS
BEGIN
    EXECUTE IMMEDIATE
    'MERGE INTO INSIS_PEOPLE_V10_TRACE.rejected_insis t ' 
    ||' USING (SELECT ID_VIGENTE FROM '|| TABLE_LOG 
           ||' WHERE ID_INSIS IS NULL ) d on (t.ID_VIGENTE = d.ID_VIGENTE ) ' 
   ||' WHEN NOT matched THEN INSERT (ID_VIGENTE, TABLE_NAME, ERROR)' 
    || 'VALUES (d.ID_VIGENTE , TABLE_LOG, :1)'
    using Param1;
END INS_REJECTED2;
/

-- ----------------------------
-- Function structure for SAMPLE_PROCEDURE
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "INSIS_PEOPLE_V10_TRACE"."SAMPLE_PROCEDURE" AS
BEGIN
	UPDATE INSIS_PEOPLE_V10_TRACE.PARAMETRICA set ESTADO = 99, MIGRADA = 1 WHERE  T_STAGE = p_table_name;  	COMMIT;	
END;
/

-- ----------------------------
-- Function structure for TEST_2
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "INSIS_PEOPLE_V10_TRACE"."TEST_2" AS
BEGIN
      execute immediate 
          'select * from INSIS_PEOPLE_V10_TRACE.'||pTableName ;  	

  END;
/

-- ----------------------------
-- Function structure for UPDATE_MY_TABLE
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "INSIS_PEOPLE_V10_TRACE"."UPDATE_MY_TABLE" AS
BEGIN
      execute immediate 
          'select * from '||pTableName ;  	COMMIT;	

  END;
/
