/*
 Navicat Premium Data Transfer

 Source Server         : INSIS_GEN_V10_FK
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : insis.cl5u1tcuiscl.us-east-1.rds.amazonaws.com:1521
 Source Schema         : INSIS_PEOPLE_V10_ERROR

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 10/01/2022 15:30:41
*/


-- ----------------------------
-- Table structure for GEN_AGENT_COMMISSIONS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."GEN_AGENT_COMMISSIONS" (
  "INSR_TYPE" NUMBER VISIBLE NOT NULL,
  "AGENT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "COMMISSION_PERCENT" NUMBER VISIBLE NOT NULL,
  "BEGIN_DATE" DATE VISIBLE NOT NULL,
  "END_DATE" DATE VISIBLE NOT NULL,
  "PRODUCTION_YEAR" NUMBER VISIBLE,
  "DURATION" NUMBER VISIBLE NOT NULL,
  "ON_INSTALL" VARCHAR2(1 BYTE) VISIBLE DEFAULT 'Y'    NOT NULL,
  "HOLD_COSTS" VARCHAR2(1 BYTE) VISIBLE DEFAULT 'N'    NOT NULL,
  "COMMISSION_TYPE" VARCHAR2(10 BYTE) VISIBLE NOT NULL,
  "SALES_CHANNEL" NUMBER(10,0) VISIBLE NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for HT_PEOPLE_GROUPS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."HT_PEOPLE_GROUPS" (
  "ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "NAME" VARCHAR2(250 BYTE) VISIBLE NOT NULL,
  "STATUS" VARCHAR2(1 BYTE) VISIBLE DEFAULT NULL NOT NULL,
  "GROUP_TYPE" VARCHAR2(10 BYTE) VISIBLE NOT NULL,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "REGISTRATION_DATE" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ACCOUNT_AGENTS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_ACCOUNT_AGENTS" (
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE NOT NULL,
  "AGENT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ACCOUNT_OFFICES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_ACCOUNT_OFFICES" (
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE NOT NULL,
  "OFFICE_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ACCOUNT_SALES_CHANNEL
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_ACCOUNT_SALES_CHANNEL" (
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE NOT NULL,
  "CHANNEL_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ADDRESS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_ADDRESS" (
  "MAN_ID" NUMBER VISIBLE,
  "ADDRESS_TYPE" VARCHAR2(10 BYTE) VISIBLE,
  "COUNTRY" VARCHAR2(250 CHAR) VISIBLE,
  "CITY" VARCHAR2(250 CHAR) VISIBLE,
  "ADDRESS" VARCHAR2(2500 CHAR) VISIBLE,
  "POST_CODE" VARCHAR2(8 BYTE) VISIBLE,
  "NOTE" VARCHAR2(100 CHAR) VISIBLE,
  "COUNTRY_CODE" VARCHAR2(3 BYTE) VISIBLE,
  "ADDRESS_ID" NUMBER VISIBLE,
  "COUNTRY_STATE" VARCHAR2(10 BYTE) VISIBLE,
  "MAIL_YN" VARCHAR2(1 BYTE) VISIBLE,
  "INVOICE_YN" VARCHAR2(1 BYTE) VISIBLE,
  "STATE_REGION" VARCHAR2(10 BYTE) VISIBLE,
  "TERRITORY_CLASSIFICATION" VARCHAR2(1000 CHAR) VISIBLE,
  "CITY_CODE" VARCHAR2(30 BYTE) VISIBLE,
  "STREET_ID" VARCHAR2(30 BYTE) VISIBLE,
  "STREET_NUMBER" VARCHAR2(10 BYTE) VISIBLE,
  "BLOCK_NUMBER" VARCHAR2(10 BYTE) VISIBLE,
  "ENTRANCE_NUMBER" VARCHAR2(10 BYTE) VISIBLE,
  "FLOOR_NUMBER" VARCHAR2(10 BYTE) VISIBLE,
  "APARTMENT_NUMBER" VARCHAR2(10 BYTE) VISIBLE,
  "QUARTER_ID" VARCHAR2(30 BYTE) VISIBLE,
  "STATE_NAME" VARCHAR2(250 CHAR) VISIBLE,
  "REGION_NAME" VARCHAR2(250 CHAR) VISIBLE,
  "QUARTER_NAME" VARCHAR2(250 CHAR) VISIBLE,
  "STREET_NAME" VARCHAR2(250 CHAR) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USAGE_DATE_FROM" DATE VISIBLE,
  "USAGE_DATE_TO" DATE VISIBLE,
  "PRIMARY_FLAG" VARCHAR2(1 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 CHAR) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_AGENTS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_AGENTS" (
  "AGENT_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "AGENT_TYPE" NUMBER(4,0) VISIBLE,
  "OFFICE_ID" NUMBER(10,0) VISIBLE,
  "QUALIF_LEVEL" VARCHAR2(2 BYTE) VISIBLE,
  "HIRE_DATE" DATE VISIBLE,
  "FIRE_DATE" DATE VISIBLE,
  "AGENT_STATE" VARCHAR2(2 BYTE) VISIBLE,
  "DEFAULT_AGENT" VARCHAR2(1 BYTE) VISIBLE,
  "MAIN_AGENT" NUMBER(10,0) VISIBLE,
  "AGENT_NO" VARCHAR2(10 CHAR) VISIBLE,
  "CONTRACT_TYPE" VARCHAR2(10 BYTE) VISIBLE,
  "CONTRACT_MONTHS" NUMBER VISIBLE,
  "ACCOUNT_NUMBER" VARCHAR2(50 BYTE) VISIBLE,
  "PREV_JOB_CONFIRM_DATE" DATE VISIBLE,
  "NOTES" VARCHAR2(100 CHAR) VISIBLE,
  "OLD_AGENT_NO" VARCHAR2(10 BYTE) VISIBLE,
  "LEAVING_REASON" VARCHAR2(20 CHAR) VISIBLE,
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE,
  "ERROR" VARCHAR2(250 CHAR) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_AGENT_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_AGENT_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "AGENT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "AGENT_TYPE" NUMBER(4,0) VISIBLE,
  "OFFICE_ID" NUMBER(10,0) VISIBLE,
  "QUALIF_LEVEL" VARCHAR2(2 BYTE) VISIBLE,
  "HIRE_DATE" DATE VISIBLE,
  "FIRE_DATE" DATE VISIBLE,
  "AGENT_STATE" VARCHAR2(2 BYTE) VISIBLE,
  "DEFAULT_AGENT" VARCHAR2(1 BYTE) VISIBLE,
  "MAIN_AGENT" NUMBER(10,0) VISIBLE,
  "AGENT_NO" VARCHAR2(10 CHAR) VISIBLE,
  "CONTRACT_TYPE" VARCHAR2(10 BYTE) VISIBLE,
  "CONTRACT_MONTHS" NUMBER VISIBLE,
  "ACCOUNT_NUMBER" VARCHAR2(50 BYTE) VISIBLE,
  "PREV_JOB_CONFIRM_DATE" DATE VISIBLE,
  "OLD_AGENT_NO" VARCHAR2(10 BYTE) VISIBLE,
  "LEAVING_REASON" VARCHAR2(20 CHAR) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_BANKS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_BANKS" (
  "BANK_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "BANK_CODE" VARCHAR2(240 BYTE) VISIBLE,
  "SWIFT_CODE" VARCHAR2(240 BYTE) VISIBLE,
  "MAIN_BANK_ID" NUMBER(10,0) VISIBLE,
  "ERROR" VARCHAR2(200 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_BANK_ACCOUNT
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_BANK_ACCOUNT" (
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "BANK_ID" NUMBER(10,0) VISIBLE,
  "ACCOUNT_NUM" VARCHAR2(50 BYTE) VISIBLE,
  "ACCOUNT_CURRENCY" VARCHAR2(3 BYTE) VISIBLE,
  "ACCOUNT_STATE" NUMBER(1,0) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "PRIMARY_FLAG" VARCHAR2(1 BYTE) VISIBLE,
  "BANK_ACC_ID" NUMBER(10,0) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_BANK_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_BANK_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "BANK_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "BANK_CODE" VARCHAR2(240 BYTE) VISIBLE,
  "SWIFT_CODE" VARCHAR2(240 BYTE) VISIBLE,
  "MAIN_BANK_ID" NUMBER(10,0) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_BENEFICIENTS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_BENEFICIENTS" (
  "BENEFICIENT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "INSURED_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "BNF_STATE" NUMBER(4,0) VISIBLE NOT NULL,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR" VARCHAR2(500 BYTE) VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CASE_NAMES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CASE_NAMES" (
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "NAME_CAPS" VARCHAR2(400 CHAR) VISIBLE,
  "NAME_GENITIVE" VARCHAR2(400 CHAR) VISIBLE,
  "NAME_VOCATIVE" VARCHAR2(400 CHAR) VISIBLE,
  "NAME_DATE" DATE VISIBLE,
  "NAME_LOC" VARCHAR2(100 CHAR) VISIBLE,
  "SNAME_LOC" VARCHAR2(100 CHAR) VISIBLE,
  "NAME_ENG" VARCHAR2(100 CHAR) VISIBLE,
  "SNAME_ENG" VARCHAR2(100 CHAR) VISIBLE,
  "NAME_FR" VARCHAR2(100 CHAR) VISIBLE,
  "SNAME_FR" VARCHAR2(100 CHAR) VISIBLE,
  "PREFIX_LOC" VARCHAR2(100 CHAR) VISIBLE,
  "SUFFIX_LOC" VARCHAR2(100 CHAR) VISIBLE,
  "PREFIX_ENG" VARCHAR2(100 CHAR) VISIBLE,
  "SUFFIX_ENG" VARCHAR2(100 CHAR) VISIBLE,
  "PREFIX_FR" VARCHAR2(100 CHAR) VISIBLE,
  "SUFFIX_FR" VARCHAR2(100 CHAR) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR" VARCHAR2(500 CHAR) VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CLIENTS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CLIENTS" (
  "CLIENT_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "OFFICIAL_STATUS" VARCHAR2(15 BYTE) VISIBLE,
  "IC_STATUS" VARCHAR2(15 BYTE) VISIBLE,
  "CORPORATE_IC_STATUS" VARCHAR2(15 BYTE) VISIBLE,
  "EMPLOYEE_STATUS" VARCHAR2(15 BYTE) VISIBLE,
  "RISK_RATING" VARCHAR2(15 BYTE) VISIBLE,
  "SEGMENT" VARCHAR2(15 BYTE) VISIBLE,
  "CUSTOMER_TYPE" VARCHAR2(15 BYTE) VISIBLE,
  "PROFITABILITY" VARCHAR2(15 BYTE) VISIBLE,
  "ACCEPT_MARKET_INFO" VARCHAR2(15 BYTE) VISIBLE,
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CLIENT_AUTH
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CLIENT_AUTH" (
  "CLIENT_ID" NUMBER(10,0) VISIBLE,
  "USER_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "PASSWD" VARCHAR2(512 BYTE) VISIBLE,
  "LANGUAGE" VARCHAR2(240 BYTE) VISIBLE,
  "WS_USERNAME" VARCHAR2(50 BYTE) VISIBLE,
  "WS_PASS" VARCHAR2(50 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CLIENT_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CLIENT_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "CLIENT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "OFFICIAL_STATUS" VARCHAR2(15 BYTE) VISIBLE,
  "IC_STATUS" VARCHAR2(15 BYTE) VISIBLE,
  "CORPORATE_IC_STATUS" VARCHAR2(15 BYTE) VISIBLE,
  "EMPLOYEE_STATUS" VARCHAR2(15 BYTE) VISIBLE,
  "RISK_RATING" VARCHAR2(15 BYTE) VISIBLE,
  "SEGMENT" VARCHAR2(15 BYTE) VISIBLE,
  "CUSTOMER_TYPE" VARCHAR2(15 BYTE) VISIBLE,
  "PROFITABILITY" VARCHAR2(15 BYTE) VISIBLE,
  "ACCEPT_MARKET_INFO" VARCHAR2(15 BYTE) VISIBLE,
  "CLIENT_USER_NAME" VARCHAR2(40 BYTE) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CONTACTS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CONTACTS" (
  "CONTACT_ID" NUMBER(14,0) VISIBLE,
  "CONTACT_TYPE" VARCHAR2(10 BYTE) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "DETAILS" VARCHAR2(100 CHAR) VISIBLE,
  "NOTE" VARCHAR2(100 CHAR) VISIBLE,
  "PRIMARY_FLAG" VARCHAR2(1 BYTE) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "LANGUAGE" VARCHAR2(15 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CONTACT_PERSONS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CONTACT_PERSONS" (
  "CONTACT_PERSON_ID" NUMBER VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "CONTACT_PERSON_NAME" VARCHAR2(400 CHAR) VISIBLE,
  "NOTE1" VARCHAR2(100 CHAR) VISIBLE,
  "NOTE2" VARCHAR2(100 CHAR) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "ERROR" VARCHAR2(250 CHAR) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CREDITORS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CREDITORS" (
  "CREDITOR_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "NOTES" VARCHAR2(160 CHAR) VISIBLE,
  "ERROR" VARCHAR2(250 CHAR) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CREDITOR_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CREDITOR_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "CREDITOR_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "NOTES" VARCHAR2(160 BYTE) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_CREDIT_CARD
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_CREDIT_CARD" (
  "CARD_ID" NUMBER VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "CC_TYPE_ID" VARCHAR2(10 BYTE) VISIBLE,
  "BILLING_ADDRESS" VARCHAR2(2500 CHAR) VISIBLE,
  "CARDHOLDER_NAME" VARCHAR2(200 CHAR) VISIBLE,
  "EXPIRY_MONTH" NUMBER(2,0) VISIBLE,
  "EXPIRY_YEAR" NUMBER(4,0) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "ATTR1" VARCHAR2(200 CHAR) VISIBLE,
  "ATTR2" VARCHAR2(200 CHAR) VISIBLE,
  "ATTR3" VARCHAR2(200 CHAR) VISIBLE,
  "ATTR4" VARCHAR2(200 CHAR) VISIBLE,
  "ATTR5" VARCHAR2(200 CHAR) VISIBLE,
  "PREFERRED_FLAG" VARCHAR2(1 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 CHAR) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_DATA_SOURCE_PERMISSION
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_DATA_SOURCE_PERMISSION" (
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "DATA_SRC" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "PERMISSION_OUT" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "PERMISSION_IN" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "VALID_FROM" DATE VISIBLE NOT NULL,
  "VALID_TO" DATE VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR" VARCHAR2(500 BYTE) VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_EXPERTS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_EXPERTS" (
  "EXPERT_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "QUALIFICATION" NUMBER(4,0) VISIBLE,
  "OEXP1" VARCHAR2(100 BYTE) VISIBLE,
  "OEXP2" VARCHAR2(100 BYTE) VISIBLE,
  "OEXP3" VARCHAR2(100 BYTE) VISIBLE,
  "OEXP4" VARCHAR2(100 BYTE) VISIBLE,
  "OEXP5" VARCHAR2(100 BYTE) VISIBLE,
  "CONTRACT_NO" VARCHAR2(10 BYTE) VISIBLE,
  "BEGIN_DATE" DATE VISIBLE,
  "END_DATE" DATE VISIBLE,
  "NOTES" VARCHAR2(100 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_EXPERT_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_EXPERT_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "EXPERT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "QUALIFICATION" NUMBER(4,0) VISIBLE NOT NULL,
  "OEXP1" VARCHAR2(100 BYTE) VISIBLE,
  "OEXP2" VARCHAR2(100 BYTE) VISIBLE,
  "OEXP3" VARCHAR2(100 BYTE) VISIBLE,
  "OEXP4" VARCHAR2(100 BYTE) VISIBLE,
  "OEXP5" VARCHAR2(100 BYTE) VISIBLE,
  "CONTRACT_NO" VARCHAR2(10 BYTE) VISIBLE,
  "BEGIN_DATE" DATE VISIBLE,
  "END_DATE" DATE VISIBLE,
  "NOTES" VARCHAR2(100 BYTE) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_INSURERS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_INSURERS" (
  "INSURER_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "INSURER_TYPE" VARCHAR2(5 BYTE) VISIBLE,
  "CURRENT_INSURER" VARCHAR2(1 BYTE) VISIBLE,
  "REG_NUM" VARCHAR2(10 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_INSURER_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_INSURER_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "INSURER_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "INSURER_TYPE" VARCHAR2(5 BYTE) VISIBLE NOT NULL,
  "CURRENT_INSURER" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "REG_NUM" VARCHAR2(10 BYTE) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_OFFICES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_OFFICES" (
  "OFFICE_ID" NUMBER(10,0) VISIBLE,
  "OFFICE_NO" VARCHAR2(10 BYTE) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "PARENT_OFFICE" NUMBER(10,0) VISIBLE,
  "DEFAULT_OFFICE" VARCHAR2(1 BYTE) VISIBLE,
  "OFFICE_CATEGORY" NUMBER VISIBLE,
  "GL_NO" VARCHAR2(10 BYTE) VISIBLE,
  "REGION_ID" NUMBER(10,0) VISIBLE,
  "COUNTRY_ID" VARCHAR2(3 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_OFFICE_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_OFFICE_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "OFFICE_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "OFFICE_NO" VARCHAR2(10 BYTE) VISIBLE NOT NULL,
  "PARENT_OFFICE" NUMBER(10,0) VISIBLE,
  "DEFAULT_OFFICE" VARCHAR2(1 BYTE) VISIBLE DEFAULT '0'    NOT NULL,
  "OFFICE_CATEGORY" NUMBER VISIBLE,
  "GL_NO" VARCHAR2(10 BYTE) VISIBLE,
  "REGION_ID" NUMBER(10,0) VISIBLE,
  "COUNTRY_ID" VARCHAR2(3 BYTE) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_OTHERS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_OTHERS" (
  "ADDRESS_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "ADDRESS_TYPE" NUMBER(4,0) VISIBLE,
  "CHANGE_DATE" DATE VISIBLE,
  "NOTES" VARCHAR2(2000 BYTE) VISIBLE,
  "OOP1" VARCHAR2(100 BYTE) VISIBLE,
  "OOP2" VARCHAR2(100 BYTE) VISIBLE,
  "OOP3" VARCHAR2(100 BYTE) VISIBLE,
  "OOP4" VARCHAR2(100 BYTE) VISIBLE,
  "OTHER_SUBTYPE" NUMBER(5,0) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_OTHER_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_OTHER_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "ADDRESS_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ADDRESS_TYPE" NUMBER(4,0) VISIBLE NOT NULL,
  "CHANGE_DATE" DATE VISIBLE DEFAULT sysdate    NOT NULL,
  "NOTES" VARCHAR2(2000 BYTE) VISIBLE,
  "OOP1" VARCHAR2(100 BYTE) VISIBLE,
  "OOP2" VARCHAR2(100 BYTE) VISIBLE,
  "OOP3" VARCHAR2(100 BYTE) VISIBLE,
  "OOP4" VARCHAR2(100 BYTE) VISIBLE,
  "OTHER_SUBTYPE" NUMBER(5,0) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_PEOPLE" (
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "MAN_COMP" NUMBER(2,0) VISIBLE,
  "EGN" VARCHAR2(50 CHAR) VISIBLE,
  "NAME" VARCHAR2(400 CHAR) VISIBLE,
  "GNAME" VARCHAR2(100 CHAR) VISIBLE,
  "SNAME" VARCHAR2(100 CHAR) VISIBLE,
  "FNAME" VARCHAR2(100 CHAR) VISIBLE,
  "BIRTH_DATE" DATE VISIBLE,
  "SEX" NUMBER(1,0) VISIBLE,
  "NOTES" VARCHAR2(200 CHAR) VISIBLE,
  "NATIONALITY" VARCHAR2(15 CHAR) VISIBLE,
  "COMP_TYPE" VARCHAR2(2 BYTE) VISIBLE,
  "NAME_SUFFIX" VARCHAR2(30 CHAR) VISIBLE,
  "NAME_PREFIX" VARCHAR2(30 CHAR) VISIBLE,
  "DATA_SOURCE" VARCHAR2(15 BYTE) VISIBLE,
  "LANGUAGE" VARCHAR2(15 BYTE) VISIBLE,
  "HOME_COUNTRY" VARCHAR2(2 BYTE) VISIBLE,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT NULL,
  "INDUSTRY_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "SUB_INDUSTRY_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "FISCAL_PERIOD" NUMBER VISIBLE,
  "CLASS_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "CLASS_SUB_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR1" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR2" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR3" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR4" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR5" VARCHAR2(50 BYTE) VISIBLE,
  "S_UPDATE" DATE VISIBLE,
  "ERROR" VARCHAR2(500 BYTE) VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_PEOPLE_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_COMP" NUMBER(2,0) VISIBLE NOT NULL,
  "EGN" VARCHAR2(50 CHAR) VISIBLE NOT NULL,
  "NAME" VARCHAR2(400 BYTE) VISIBLE NOT NULL,
  "GNAME" VARCHAR2(100 BYTE) VISIBLE,
  "SNAME" VARCHAR2(100 BYTE) VISIBLE,
  "FNAME" VARCHAR2(100 BYTE) VISIBLE,
  "BIRTH_DATE" DATE VISIBLE,
  "SEX" NUMBER(1,0) VISIBLE,
  "NOTES" VARCHAR2(200 CHAR) VISIBLE,
  "NATIONALITY" VARCHAR2(15 BYTE) VISIBLE,
  "COMP_TYPE" VARCHAR2(2 BYTE) VISIBLE,
  "NAME_SUFFIX" VARCHAR2(30 BYTE) VISIBLE,
  "NAME_PREFIX" VARCHAR2(30 BYTE) VISIBLE,
  "DATA_SOURCE" VARCHAR2(15 BYTE) VISIBLE,
  "LANGUAGE" VARCHAR2(15 BYTE) VISIBLE,
  "HOME_COUNTRY" VARCHAR2(2 BYTE) VISIBLE,
  "INDUSTRY_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "SUB_INDUSTRY_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "FISCAL_PERIOD" NUMBER VISIBLE,
  "CLASS_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "CLASS_SUB_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR1" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR2" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR3" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR4" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR5" VARCHAR2(50 BYTE) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_GROUPS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_PEOPLE_GROUPS" (
  "GROUP_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "NOTES" VARCHAR2(60 CHAR) VISIBLE,
  "GROUP_CODE" VARCHAR2(20 BYTE) VISIBLE,
  "FROM_DATE" DATE VISIBLE,
  "TO_DATE" DATE VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_ID_LIST
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_PEOPLE_ID_LIST" (
  "LIST_ID" NUMBER VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ID_TYPE" VARCHAR2(10 BYTE) VISIBLE,
  "ID_NUMBER" VARCHAR2(50 BYTE) VISIBLE,
  "VALID_FROM" DATE VISIBLE DEFAULT SYSDATE,
  "VALID_TO" DATE VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR" VARCHAR2(500 BYTE) VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_PEOPLE_RELATION
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_PEOPLE_RELATION" (
  "PART1_ID" NUMBER(10,0) VISIBLE,
  "PART2_ID" NUMBER(10,0) VISIBLE,
  "REL_ID" NUMBER(10,0) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_REGIONS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_REGIONS" (
  "REGION_ID" NUMBER(10,0) VISIBLE,
  "REGION_NAME" VARCHAR2(200 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ROLE
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_ROLE" (
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "ROLE_ID" NUMBER(4,0) VISIBLE,
  "ERROR" CHAR(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ROLE_AGENTS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_ROLE_AGENTS" (
  "ROLE_ID" VARCHAR2(40 BYTE) VISIBLE NOT NULL,
  "AGENT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ROLE_INSRTYPES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_ROLE_INSRTYPES" (
  "ROLE_ID" VARCHAR2(40 BYTE) VISIBLE NOT NULL,
  "INSR_TYPE" NUMBER VISIBLE NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_ROLE_OFFICES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_ROLE_OFFICES" (
  "ROLE_ID" VARCHAR2(40 BYTE) VISIBLE NOT NULL,
  "OFFICE_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER(10,0) VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_SALES_CHANNEL
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_SALES_CHANNEL" (
  "CHANNEL_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "CHANNEL_TYPE" VARCHAR2(20 BYTE) VISIBLE,
  "CHANNEL_SUBTYPE" VARCHAR2(10 BYTE) VISIBLE,
  "MAIN_CHANNEL" NUMBER(10,0) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_SALES_CHANNEL_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_SALES_CHANNEL_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "CHANNEL_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "CHANNEL_TYPE" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "CHANNEL_SUBTYPE" VARCHAR2(10 BYTE) VISIBLE,
  "MAIN_CHANNEL" NUMBER(10,0) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_SALES_UNIT
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_SALES_UNIT" (
  "SALE_UNIT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "UNIT_AGENT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "AGENT_ID" NUMBER(10,0) VISIBLE,
  "OFFICE_ID" NUMBER(10,0) VISIBLE,
  "SALE_OFFICE_ID" NUMBER(10,0) VISIBLE,
  "SALES_CHANEL_ID" NUMBER(10,0) VISIBLE,
  "INSR_TYPE" NUMBER VISIBLE,
  "COMMISSION_TYPE" VARCHAR2(10 BYTE) VISIBLE,
  "COMM_SHARE" NUMBER VISIBLE,
  "COMM_PRC" NUMBER VISIBLE,
  "VALID_FROM" DATE VISIBLE NOT NULL,
  "VALID_TO" DATE VISIBLE,
  "NOTES" VARCHAR2(1000 BYTE) VISIBLE,
  "ATTR1" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR2" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR3" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR4" VARCHAR2(50 BYTE) VISIBLE,
  "ATTR5" VARCHAR2(50 BYTE) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_SEARCH_INFO
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_SEARCH_INFO" (
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ROLE_ID" NUMBER(4,0) VISIBLE,
  "REFERENCE_ID" NUMBER VISIBLE,
  "SEARCH_INFO" VARCHAR2(4000 CHAR) VISIBLE NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_STAFF
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_STAFF" (
  "STAFF_ID" NUMBER(10,0) VISIBLE,
  "MAN_ID" NUMBER(10,0) VISIBLE,
  "OCUPATION" NUMBER(4,0) VISIBLE,
  "SECURITY_ID" VARCHAR2(40 BYTE) VISIBLE,
  "MAX_QUAL_LEVEL" NUMBER(10,0) VISIBLE,
  "OFFICE_ID" NUMBER(10,0) VISIBLE,
  "PERIOD_ID" NUMBER VISIBLE,
  "FL_MANY_PERIODS" NUMBER VISIBLE,
  "SENIOR" NUMBER(10,0) VISIBLE,
  "USER_EMAIL" VARCHAR2(100 BYTE) VISIBLE,
  "LANGUAGE" VARCHAR2(240 BYTE) VISIBLE,
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_STAFF_CHANGES
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_STAFF_CHANGES" (
  "CHANGE_ID" NUMBER VISIBLE NOT NULL,
  "STAFF_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MAN_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "OCUPATION" NUMBER(4,0) VISIBLE,
  "SECURITY_ID" VARCHAR2(40 BYTE) VISIBLE,
  "MAX_QUAL_LEVEL" NUMBER(10,0) VISIBLE,
  "OFFICE_ID" NUMBER(10,0) VISIBLE,
  "PERIOD_ID" NUMBER VISIBLE,
  "FL_MANY_PERIODS" NUMBER VISIBLE DEFAULT 0,
  "SENIOR" NUMBER(10,0) VISIBLE,
  "USER_EMAIL" VARCHAR2(100 BYTE) VISIBLE,
  "LANGUAGE" VARCHAR2(240 BYTE) VISIBLE,
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE,
  "VALID_FROM" DATE VISIBLE,
  "VALID_TO" DATE VISIBLE,
  "USERNAME" VARCHAR2(40 BYTE) VISIBLE DEFAULT SYS_CONTEXT( 'INSISCTX', 'USERNAME' )    NOT NULL,
  "REGISTRATION_DATE" DATE VISIBLE DEFAULT SYSDATE    NOT NULL,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for P_USER_ACCOUNTS
-- ----------------------------
CREATE TABLE "INSIS_PEOPLE_V10_ERROR"."P_USER_ACCOUNTS" (
  "ACCOUNT_ID" NUMBER(20,0) VISIBLE,
  "USER_NAME" VARCHAR2(40 BYTE) VISIBLE,
  "USER_EMAIL" VARCHAR2(100 BYTE) VISIBLE,
  "LANGUAGE" VARCHAR2(20 BYTE) VISIBLE,
  "COUNTRY" VARCHAR2(3 BYTE) VISIBLE,
  "LOCK_ACCOUNT" VARCHAR2(1 BYTE) VISIBLE,
  "LOCK_ACCOUNT_DATE" DATE VISIBLE,
  "CHANGE_PWD" VARCHAR2(1 BYTE) VISIBLE,
  "PWD_EXPIRE_DATE" DATE VISIBLE,
  "ERROR" VARCHAR2(250 BYTE) VISIBLE,
  "UPDATE_DATE" DATE VISIBLE,
  "INSERT_DATE" DATE VISIBLE,
  "BATCH_ID" NUMBER VISIBLE,
  "ERROR_DATE" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
